// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.3
// source: api.proto

package disgorgeapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DisgorgeServiceClient is the client API for DisgorgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DisgorgeServiceClient interface {
	Query(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type disgorgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDisgorgeServiceClient(cc grpc.ClientConnInterface) DisgorgeServiceClient {
	return &disgorgeServiceClient{cc}
}

func (c *disgorgeServiceClient) Query(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/disgorgeapi.DisgorgeService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisgorgeServiceServer is the server API for DisgorgeService service.
// All implementations must embed UnimplementedDisgorgeServiceServer
// for forward compatibility
type DisgorgeServiceServer interface {
	Query(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedDisgorgeServiceServer()
}

// UnimplementedDisgorgeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDisgorgeServiceServer struct {
}

func (UnimplementedDisgorgeServiceServer) Query(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedDisgorgeServiceServer) mustEmbedUnimplementedDisgorgeServiceServer() {}

// UnsafeDisgorgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisgorgeServiceServer will
// result in compilation errors.
type UnsafeDisgorgeServiceServer interface {
	mustEmbedUnimplementedDisgorgeServiceServer()
}

func RegisterDisgorgeServiceServer(s grpc.ServiceRegistrar, srv DisgorgeServiceServer) {
	s.RegisterService(&DisgorgeService_ServiceDesc, srv)
}

func _DisgorgeService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisgorgeServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/disgorgeapi.DisgorgeService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisgorgeServiceServer).Query(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// DisgorgeService_ServiceDesc is the grpc.ServiceDesc for DisgorgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DisgorgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "disgorgeapi.DisgorgeService",
	HandlerType: (*DisgorgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _DisgorgeService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
